language: generic
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - "python3"
          - "python3-pip"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - os: osx
    language: c++
    compiler: clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${MATRIX_EVAL}"; sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc; sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++; gcc -v; fi
script:
  - set -e
  - git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make bsd CXX=clang++ -C maiken; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make nix -C maiken; fi
  - mv maiken/mkn .
  - python3 -m pip install pip --upgrade --user
  - python3 -m pip install numpy --upgrade --user
  - MKN_LIB_LINK_LIB=1 KLOG=3 ./mkn build -tOa "-fPIC -std=c++14" -d
  - MKN_LIB_LINK_LIB=1 KLOG=3 ./mkn build -tOa "-fPIC -std=c++14" -p test run -l "-pthread -ldl"
