version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2019

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - SET PATH=C:\Program Files\Git\usr\bin;%PATH%
  - SET MKN_CL_PREFERRED=1
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - C:\Python36-x64\Scripts\pip install numpy
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; KLOG=3 ./mkn clean build -dtO"
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; KLOG=3 ./mkn clean build -tOp test run"
